# Generated by Django 6.0.2 on 2026-03-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_emp_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
